python run_search.py -p 1 -s 1
python run_search.py -p 1 -s 2
python run_search.py -p 1 -s 3
python run_search.py -p 1 -s 4
python run_search.py -p 1 -s 5
python run_search.py -p 1 -s 6
python run_search.py -p 1 -s 7
python run_search.py -p 1 -s 8
python run_search.py -p 1 -s 9
python run_search.py -p 1 -s 10